Repository zetkin/organize.zetk.in, pull requests merged in 2018-07, with the labels that each got.

#818 Phonebanking privacy
  locale/forms/callAssignment/en.yaml
  locale/forms/callAssignment/sv.yaml
  locale/forms/personTag/en.yaml
  locale/forms/personTag/sv.yaml
  src/components/forms/CallAssignmentForm.jsx
  src/components/forms/PersonTagForm.jsx
Labels: feature

#821 Minor improvements
  locale/panes/allCampaigns/en.yaml
  src/actions/actionResponse.js
  src/actions/index.js
  src/components/panes/ActionPane.jsx
  src/components/panes/ImportActionsPane.jsx
  src/store/actionResponses.js
  src/utils/import.js
Labels: bug, enhancement, feature

#826 Lazy-loaded lists
  src/components/lists/List.jsx
  src/components/lists/items/ActionListItem.jsx
  src/components/lists/items/ListItem.jsx
  src/store/actionResponses.js
  src/store/participants.js
Labels: feature

#830 Alt phone
  locale/forms/person/en.yaml
  locale/forms/person/sv.yaml
  locale/panes/import/en.yaml
  locale/panes/import/sv.yaml
  src/actions/person.js
  src/components/forms/PersonForm.jsx
  src/components/lists/items/PersonListItem.jsx
  src/components/misc/importer/ImporterColumnHead.jsx
  src/components/misc/importer/settings/PersonDataColumnSettings.jsx
  src/components/panes/AddPersonPane.jsx
  src/components/panes/PersonPane.jsx
  src/store/view.js
Labels: feature

#834 Whitespaces during people merge
  src/components/panes/MergePeoplePane.jsx
  src/server/api/duplicates.js
Labels: bug

#836 Campaign visibility
  locale/forms/campaign/en.yaml
  locale/forms/campaign/sv.yaml
  locale/lists/campaignList/en.yaml
  locale/lists/campaignList/sv.yaml
  locale/panes/allCampaigns/en.yaml
  src/components/forms/CampaignForm.jsx
  src/components/lists/items/CampaignListItem.jsx
Labels: feature

#837 Hide queue details for huge assignments
  locale/panes/callAssignment/en.yaml
  locale/panes/callAssignment/sv.yaml
  src/components/panes/CallAssignmentPane.jsx
Labels: chore

#840 Query improvements
  locale/filters/callHistory/en.yaml
  locale/filters/callHistory/sv.yaml
  locale/panes/query/en.yaml
  locale/panes/query/sv.yaml
  src/components/filters/CallHistoryFilter.jsx
  src/components/filters/CallHistoryFilter.scss
  src/components/panes/QueryPane.jsx
Labels: enhancement, feature

#841 Minimum search string
  locale/header/en.yaml
  locale/header/sv.yaml
  src/actions/search/index.js
  src/components/header/search/Search.jsx
  src/components/header/search/Search.scss
Labels: enhancement

#848 Person drag and drop bug
  src/components/lists/items/ActionListItem.jsx
Labels: bug

#851 More filters
  locale/filters/campaign/en.yaml
  locale/filters/campaign/sv.yaml
  locale/filters/en.yaml
  locale/filters/subQuery/en.yaml
  locale/filters/subQuery/sv.yaml
  locale/filters/sv.yaml
  src/components/filters/CampaignFilter.jsx
  src/components/filters/FilterList.jsx
  src/components/filters/SubQueryFilter.jsx
  src/components/filters/index.js
  src/components/forms/inputs/SelectInput.jsx
Labels: enhancement, feature
