Repository zetkin/organize.zetk.in, pull requests merged in 2018-08, with the labels that each got.

#864 Minor bugs from today's hackathon
  src/components/App.jsx
  src/components/App.scss
  src/components/lists/List.jsx
Labels: bug

#870 Export action info
  locale/bulkOps/en.yaml
  locale/bulkOps/sv.yaml
  locale/lists/actionList/en.yaml
  locale/panes/bulkOp/en.yaml
  locale/panes/bulkOp/sv.yaml
  src/components/lists/ActionList.jsx
  src/components/lists/ActionList.scss
  src/components/lists/List.jsx
  src/components/lists/List.scss
  src/components/lists/PersonList.scss
  src/components/lists/items/ActionListItem.jsx
  src/components/lists/items/ActionListItem.scss
  src/components/lists/items/ListItem.scss
  src/components/lists/items/elements/ParticipantList.scss
  src/components/sections/campaign/AllActionsPane.jsx
  src/server/api/bulk.js
Labels: feature

#871 Intro tweaks
  src/components/App.jsx
  src/components/App.scss
  src/scss/_mixins.scss
Labels: enhancement

#880 List optimization
  package.json
  src/components/lists/ActionList.jsx
  src/components/lists/List.jsx
  src/components/lists/items/ActionListItem.jsx
  src/components/lists/items/ListItem.jsx
  src/components/sections/campaign/AllActionsPane.jsx
  src/store/actionResponses.js
  src/store/actions.js
  src/store/index.js
  src/store/participants.js
Labels: enhancement, optimization

#879 show loading indicator in all actions pane
  src/components/sections/campaign/AllActionsPane.jsx
Labels: enhancement

#881 Search improvements
  src/actions/search/procs.js
  src/actions/search/utils.js
  src/components/header/search/Search.scss
  src/store/search.js
Labels: enhancement

#882 Easier selection of persons
  src/components/misc/PersonSelectWidget.jsx
  src/components/misc/PersonSelectWidget.scss
  src/components/misc/personcollection/PersonCollection.jsx
  src/components/misc/personcollection/PersonCollection.scss
  src/components/panes/ActionPane.jsx
  src/scss/_mixins.scss
  src/utils/store.js
Labels: bug, enhancement

#883 Implement loading state for Avatar images
  src/components/lists/items/elements/ParticipantItem.scss
  src/components/misc/Avatar.jsx
  src/components/misc/Avatar.scss
  src/components/misc/DraggableAvatar.scss
Labels: enhancement

#884 Change merge objects
  locale/panes/managePeople/en.yaml
  locale/panes/managePeople/sv.yaml
  locale/panes/mergePeople/en.yaml
  locale/panes/mergePeople/sv.yaml
  src/actions/index.js
  src/actions/person.js
  src/components/misc/personcollection/PersonCollection.jsx
  src/components/misc/personcollection/items/PCDuplicateItem.jsx
  src/components/misc/personcollection/items/PCDuplicateItem.scss
  src/components/misc/personcollection/items/index.js
  src/components/panes/ActionPane.jsx
  src/components/panes/CallAssignmentPane.jsx
  src/components/panes/MergePeoplePane.jsx
  src/components/panes/PersonPane.jsx
  src/store/people.js
Labels: feature

#885 Tweak cap message in ActionExportBulkOpConfig
  locale/panes/bulkOp/en.yaml
  locale/panes/bulkOp/sv.yaml
  src/components/bulk/config/ActionExportBulkOpConfig.scss
Labels: enhancement

#891 Avatar sizing (and other improvements)
  src/actions/search/index.js
  src/components/header/search/matches/MatchBase.scss
  src/components/lists/items/elements/ParticipantItem.scss
  src/components/lists/items/elements/ParticipantList.scss
Labels: bug, enhancement

#896 Action day search fixes
  src/actions/search/procs.js
  src/components/panes/ActionDayPane.jsx
Labels: bug

#897 Action pane improvements
  src/components/misc/PersonSelectWidget.jsx
  src/components/misc/personcollection/PersonCollection.jsx
  src/components/panes/ActionPane.jsx
  src/store/participants.js
Labels: enhancement

#895 Timeline
  locale/panes/person/en.yaml
  locale/panes/person/sv.yaml
  locale/panes/personTimeline/en.yaml
  locale/timeline/en.yaml
  locale/timeline/sv.yaml
  src/actions/index.js
  src/actions/timeline.js
  src/components/misc/timeline/PersonTimeline.jsx
  src/components/misc/timeline/PersonTimeline.scss
  src/components/misc/timeline/renderers/ActionTimelineEvent.jsx
  src/components/misc/timeline/renderers/ActionTimelineEvent.scss
  src/components/misc/timeline/renderers/MultiActionTimelineEvent.jsx
  src/components/misc/timeline/renderers/MultiActionTimelineEvent.scss
  src/components/misc/timeline/renderers/TimelineEvent.jsx
  src/components/misc/timeline/renderers/TimelineEvent.scss
  src/components/panes/PersonPane.jsx
  src/components/panes/PersonPane.scss
  src/components/panes/PersonTimelinePane.jsx
  src/components/panes/index.js
  src/store/index.js
  src/store/timelines.js
Labels: feature, platform

#905 Action filters
  locale/panes/allActions/en.yaml
  locale/panes/allActions/sv.yaml
  src/actions/action.js
  src/components/sections/campaign/ActionDistributionPane.jsx
  src/components/sections/campaign/AllActionsPane.jsx
  src/components/sections/campaign/CampaignPlaybackPane.jsx
  src/components/sections/campaign/CampaignSectionPaneBase.jsx
  src/store/actions.js
Labels: feature

#910 Misc issues
  src/components/misc/timeline/renderers/ActionTimelineEvent.jsx
  src/components/misc/timeline/renderers/MultiActionTimelineEvent.jsx
  src/components/panes/ActionDayPane.jsx
  src/components/panes/EditQueryPane.jsx
  src/components/sections/Section.jsx
  src/utils/PaneManager.js
Labels: bug
