Repository zetkin/organize.zetk.in, pull requests merged in 2019-03, with the labels that each got.

#977 Refactor search store to handle multiple searches
  src/actions/search/index.js
  src/actions/search/utils.js
  src/components/KeyboardShortcuts.jsx
  src/components/forms/inputs/RelSelectInput.jsx
  src/components/header/search/ScopeSelect.jsx
  src/components/header/search/Search.jsx
  src/components/misc/PersonSelectWidget.jsx
  src/store/search.js
Labels: enhancement

#984 Bulk delete bug fixes
  src/actions/bulk.js
  src/components/sections/people/PeopleListPane.jsx
  src/server/api/bulk.js
  src/store/people.js
Labels: bug

#985 Fix bug in ActionList lazy loading
  src/components/lists/List.jsx
  src/components/lists/items/ActionListItem.jsx
Labels: bug

#980 Survey linking hints
  locale/panes/linkSubmission/en.yaml
  src/components/panes/AddPersonPane.jsx
  src/components/panes/LinkSubmissionPane.jsx
  src/components/panes/LinkSubmissionPane.scss
Labels: feature

#1000 Most active filter
  locale/filters/en.yaml
  locale/filters/mostActive/en.yaml
  src/components/filters/CampaignFilter.jsx
  src/components/filters/FilterList.jsx
  src/components/filters/FilterTimeFrameSelect.jsx
  src/components/filters/MostActiveFilter.jsx
  src/components/filters/index.js
Labels: feature
